name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Publish
      run: dotnet publish src/apca/apca.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: apca
        path: src/apca/bin/Release/net6.0-windows/win-x64/publish/apca.exe