name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3    # Updated to v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3    # Updated to v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Publish
      run: dotnet publish src/apca/apca.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableWindowsTargeting=true
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3    # Updated to v3
      with:
        name: apca-${{ github.sha }}    # Added SHA for versioning
        path: |                         # Added multiple files
          src/apca/bin/Release/net6.0-windows/win-x64/publish/apca.exe
          src/apca/bin/Release/net6.0-windows/win-x64/publish/*.dll
        retention-days: 90              # Added retention period